#!/bin/bash

# Test script to verify sentence index validation fix

echo "=========================================="
echo "Testing Sentence Index Validation Fix"
echo "=========================================="
echo ""

echo "This script demonstrates the fix for sentence index validation."
echo "It shows that:"
echo "  - Empty files: Can write to sentence 0"
echo "  - Files ending WITHOUT delimiters: Cannot access next sentence index"
echo "  - Files ending WITH delimiters: Can access next sentence index"
echo ""

echo "Prerequisites:"
echo "  1. Name server running on port 8080"
echo "  2. Storage server running on ports 9000/9001"
echo ""

echo "Manual Test Steps:"
echo ""

echo "=========================================="
echo "TEST 0: Empty file (NEW FIX)"
echo "=========================================="
echo "Step 1: Create an empty file"
echo "  Commands:"
echo "    CREATE empty_test.txt"
echo ""
echo "Step 2: Try to write to sentence 0 (should SUCCEED)"
echo "  Commands:"
echo "    WRITE empty_test.txt 0"
echo "    0 First sentence content"
echo "    ETIRW"
echo ""
echo "  Expected result:"
echo "    ✅ ACK: Sentence locked. Send word updates, end with ETIRW"
echo "    ✅ Write Successful! Sentence 0 updated."
echo ""

echo "=========================================="
echo "TEST 1: File without delimiter"
echo "=========================================="
echo "Step 1: Create file with content without delimiter"
echo "  Commands:"
echo "    CREATE test_no_delim.txt"
echo "    WRITE test_no_delim.txt 0"
echo "    0 Hello world"
echo "    ETIRW"
echo ""
echo "Step 2: Try to access sentence 1 (should FAIL)"
echo "  Commands:"
echo "    WRITE test_no_delim.txt 1"
echo ""
echo "  Expected result:"
echo "    ❌ ERROR: Sentence index out of range (0-0). Last sentence has no delimiter."
echo ""

echo "=========================================="
echo "TEST 2: File with delimiter"
echo "=========================================="
echo "Step 1: Create file with content ending with delimiter"
echo "  Commands:"
echo "    CREATE test_with_delim.txt"
echo "    WRITE test_with_delim.txt 0"
echo "    0 Hello world."
echo "    ETIRW"
echo ""
echo "Step 2: Try to access sentence 1 (should SUCCEED)"
echo "  Commands:"
echo "    WRITE test_with_delim.txt 1"
echo "    0 New sentence here"
echo "    ETIRW"
echo ""
echo "  Expected result:"
echo "    ✅ ACK: Sentence locked. Send word updates, end with ETIRW"
echo "    ✅ Write Successful! Sentence 1 updated."
echo ""

echo "=========================================="
echo "TEST 3: Fix incomplete sentence"
echo "=========================================="
echo "Step 1: File has incomplete sentence"
echo "  Content: 'Hello world' (no delimiter)"
echo ""
echo "Step 2: Add delimiter to complete it"
echo "  Commands:"
echo "    WRITE test_no_delim.txt 0"
echo "    2 everyone."
echo "    ETIRW"
echo ""
echo "Step 3: Now try to access sentence 1 (should SUCCEED)"
echo "  Commands:"
echo "    WRITE test_no_delim.txt 1"
echo "    0 This works now"
echo "    ETIRW"
echo ""
echo "  Expected result:"
echo "    ✅ Write Successful! (because sentence 0 now ends with '.')"
echo ""

echo "=========================================="
echo "To run the actual tests:"
echo "=========================================="
echo "1. Start servers:"
echo "   Terminal 1: /home/manik/Desktop/Main_project/Course_project_osn/name_server"
echo "   Terminal 2: /home/manik/Desktop/Main_project/Course_project_osn/storage_server 9000 9001"
echo ""
echo "2. Run client:"
echo "   Terminal 3: /home/manik/Desktop/Main_project/Course_project_osn/client"
echo ""
echo "3. Execute the commands shown in the tests above"
echo ""

echo "=========================================="
echo "Quick Verification Commands"
echo "=========================================="
echo ""
echo "# Test 0: Empty file (should allow sentence 0):"
echo "CREATE empty.txt"
echo "WRITE empty.txt 0"
echo "0 Hello world"
echo "ETIRW"
echo ""
echo "# Test 1: File without delimiter (should reject index 1):"
echo "CREATE test1.txt"
echo "WRITE test1.txt 0"
echo "0 Hello world"
echo "ETIRW"
echo "WRITE test1.txt 1  # <- Should fail"
echo ""
echo "# Test 2: File with delimiter (should allow index 1):"
echo "CREATE test2.txt"
echo "WRITE test2.txt 0"
echo "0 Hello world."
echo "ETIRW"
echo "WRITE test2.txt 1  # <- Should succeed"
echo "0 New sentence"
echo "ETIRW"
echo ""
